import * as PDFDocument from "pdfkit";
import type { WorkflowResult } from "../types/workflow.types";

export async function generatePdfReport(
  workflow: WorkflowResult,
  metadata: {
    owner: string;
    repo: string;
    pullNumber: number;
    commitSha: string;
  }
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50, bufferPages: true });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // SECTION 1 — Cover Page
    doc.font("Helvetica-Bold").fontSize(32).fillColor("black").text("Fixor Security Report", { align: "center" });
    doc.moveDown(0.5);
    doc.font("Helvetica").fontSize(14).fillColor("gray").text("Automated vulnerability analysis", { align: "center" });
    doc.moveDown(2);

    doc.strokeColor("#cccccc").lineWidth(1).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
    doc.moveDown(1.5);

    const dateStr = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

    doc.font("Helvetica").fontSize(12).fillColor("black");
    doc.text(`Repository: ${metadata.owner}/${metadata.repo}`);
    doc.text(`Pull Request: #${metadata.pullNumber}`);
    doc.text(`Commit: ${metadata.commitSha.slice(0, 12)}`);
    doc.text(`Generated: ${dateStr}`);

    doc.addPage();

    // SECTION 2 — Executive Summary
    doc.font("Helvetica-Bold").fontSize(20).text("Executive Summary");
    doc.moveDown();

    const addRow = (label: string, value: string | number) => {
      doc.font("Helvetica-Bold").fontSize(12).text(`${label}: `, { continued: true });
      doc.font("Helvetica").text(String(value));
      doc.moveDown(0.5);
    };

    addRow("Workflow status", workflow.status);
    addRow("Total findings", workflow.totalFindings);
    addRow("Vulnerabilities found", workflow.sqlInjectionFindings);
    addRow("Fixes generated", workflow.fixesGenerated);
    addRow("High quality patches", workflow.highQualityPatches);
    addRow("Medium quality patches", workflow.mediumQualityPatches);
    addRow("Low quality patches", workflow.lowQualityPatches);
    addRow("Analysis duration", `${workflow.timing.durationMs} ms`);
    addRow("Automation ready", workflow.automationReady ? "Yes" : "No");

    if (workflow.fixes.length > 0) {
      doc.addPage();
    }

    // SECTION 3 — Detailed Findings
    for (let i = 0; i < workflow.fixes.length; i++) {
        const fix = workflow.fixes[i];

        doc.font("Helvetica-Bold").fontSize(16).text(`Finding: ${fix.file}:${fix.line}`);
        doc.moveDown(0.5);
        doc.font("Helvetica").fontSize(10).text(`Type: ${fix.type}`);
        doc.text(`Patch quality: ${fix.patchQuality}`);
        doc.text(`Confidence: ${fix.confidence}`);
        doc.moveDown();

        doc.font("Helvetica-Bold").fontSize(12).text("Explanation:");
        doc.font("Helvetica").fontSize(11).text(fix.explanation);
        doc.moveDown();

        const truncateStr = (str: string, max: number) => 
            str.length > max ? str.substring(0, max - 3) + "..." : str;

        const originalSafe = truncateStr(fix.originalCode, 500);
        const fixedSafe = truncateStr(fix.fixedCode, 500);

        doc.font("Helvetica-Bold").fontSize(12).text("Original code:");
        doc.font("Courier").fontSize(9).text(originalSafe);
        doc.moveDown();

        doc.font("Helvetica-Bold").fontSize(12).text("Suggested fix:");
        doc.font("Courier").fontSize(9).text(fixedSafe);

        if (i < workflow.fixes.length - 1) {
            doc.addPage();
        }
    }

    // Apply global footer
    const range = doc.bufferedPageRange();
    const totalPages = range.count;
    for (let i = 0; i < totalPages; i++) {
      doc.switchToPage(range.start + i);
      const bottom = doc.page.margins.bottom;
      doc.page.margins.bottom = 0;
      doc.font("Helvetica").fontSize(9).fillColor("gray");
      doc.text(
        `Generated by Fixor · fixor-production.up.railway.app          Page ${i + 1} of ${totalPages}`,
        50,
        doc.page.height - 35,
        { align: "center", width: doc.page.width - 100, lineBreak: false }
      );
      doc.page.margins.bottom = bottom;
    }

    doc.end();
  });
}
